# Dockerfile for installing Python dependencies
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

#COPY requirements.txt /app/requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["echo", "Python dependencies installed successfully."]
