name: Unit Tests and Publish

on:
  push:
    branches:
      - "[0-9]+.0"
      - "[0-9]+.0-*"
    paths:
      - "**/workflows/**"
      - "**/resources/**"
      - "Dockerfile"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.sha }}

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build_and_publish
    services:
      db:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          # Replace this with your unit test command
          echo "Running unit tests..."

